### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 6r1d** [BinaryNate/midi-message-parser#1]
Hello. :-)
Could you add some license file like MIT I saw in [your other project](https://github.com/BinaryNate/voxophone/blob/master/LICENSE), please?
Apparently, projects with no license [are not considered open-source or free](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).
Thanks!

**Comment by binarynate** [comment]
Sure! I just added an MIT license.

**Comment by 6r1d** [comment]
Thanks a lot!

**Comment by binarynate** [comment]
You're welcome!
